version: "2.0"
services:
  main:
    image: chandrastation/pkt_on_akash:latest
    env:
      - PAYMENT_ADDR=<PKT_Wallet>
      - POOL1=http://pool.pkteer.com
      - POOL2=http://pool.pktpool.io
      - POOL3=http://pool.pkt.world
      - POOL4=http://pool.srizbi.com 
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    miner:
      resources:
        cpu:
          units: 1
        memory:
          size: 1 Gi
        storage:
          size: 1 Gi
  placement:
    any:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        miner:
          denom: uakt
          amount: 1000

deployment:
  main:
    any:
      profile: miner
      count: 1
